version: "3.7"
services:
  app:
    build:
      args:
        user: aoddy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel_test
    container_name: laravel_test-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel_test

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_test

  nginx:
    image: nginx:alpine
    container_name: laravel_test-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - laravel_test

networks:
  laravel_test:
    driver: bridge
